// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zHQrRkbbjRrWx2O8Aqxsy0pvhzFZt5c',
    appId: '1:736662120288:web:b9fac0dc388398f6246005',
    messagingSenderId: '736662120288',
    projectId: 'help-for-study-app',
    authDomain: 'help-for-study-app.firebaseapp.com',
    storageBucket: 'help-for-study-app.firebasestorage.app',
    measurementId: 'G-31EKW1C6CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNOwpOaIYPIL5LMZd5CbB3LoQU9YWNZM',
    appId: '1:736662120288:android:097c52653e13846b246005',
    messagingSenderId: '736662120288',
    projectId: 'help-for-study-app',
    storageBucket: 'help-for-study-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvIoZAebiaGXprdZ3PmlymQtpVFDMLss',
    appId: '1:736662120288:ios:42c2eb9a8f6a7004246005',
    messagingSenderId: '736662120288',
    projectId: 'help-for-study-app',
    storageBucket: 'help-for-study-app.firebasestorage.app',
    iosBundleId: 'com.example.helperForStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvIoZAebiaGXprdZ3PmlymQtpVFDMLss',
    appId: '1:736662120288:ios:42c2eb9a8f6a7004246005',
    messagingSenderId: '736662120288',
    projectId: 'help-for-study-app',
    storageBucket: 'help-for-study-app.firebasestorage.app',
    iosBundleId: 'com.example.helperForStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_zHQrRkbbjRrWx2O8Aqxsy0pvhzFZt5c',
    appId: '1:736662120288:web:b91419043bc4843b246005',
    messagingSenderId: '736662120288',
    projectId: 'help-for-study-app',
    authDomain: 'help-for-study-app.firebaseapp.com',
    storageBucket: 'help-for-study-app.firebasestorage.app',
    measurementId: 'G-LZ7B09YYSY',
  );

}